spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/pedidos}
    username: ${DB_USERNAME:pedidos}
    password: ${DB_PASSWORD:pedidos}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: PEDIDOS_POOL
      connection-test-query: ${POOL_TEST_QUERY:SELECT 1}
      connection-timeout: ${POOL_TIMEOUT:300000}
      maximum-pool-size: ${POOL_MAX_SIZE:2}
      max-lifetime: ${POOL_MAX_LIFETIME:1800000}
      minimum-idle: ${POOL_MIN_IDLE:50000}
      validation-timeout: ${POOL_VALIDATION_TIMEOUT:300000}
      idle-timeout: ${POOL_IDLE_TIMEOUT:600000}
  output:
    ansi:
      enabled: always